### ISSUE TITLE
tensorflow version mismatch

### ISSUE THREAD

**Issue by Chu-Ping** [ThFriedrich/airpi#1]
cvnn.layers.convolutional asks for tensorflow 2.12, 
maybe upgrade it in the dockerfile

**Comment by ThFriedrich** [comment]
I figured it's safer to specify cvnn and a corresponding tensorflow_probability version which actually caused the conflict. This should now be stable against tensorflow 2.11.

**Comment by ThFriedrich** [comment]
I tested this and it seems to work so I'm closing this issue. Reopen if issues persist.
