### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by Psiche91** [ThFriedrich/airpi#2]
Hi, I am new to the Python language.  
But while following the tutorial ('AIRPI Demonstration Notebook').
I get stuck at line three.  
Basically, I don't have the module ap_reconstruction.  
So the question is very simple: how do I install airpi?"

**Comment by ThFriedrich** [comment]
Hello,

there is no actual installation required. Everything in the repository is plain python code, structured in a way that python will recognize. If you cloned the repository and the notebook is in its original location ti should find "ap_reconstruction" and all the other "ap_xxx" modules. Make sure the "airpi" folder is your workspace directory. If you're facing more problems, please provide more information on your setup (OS, Editor, GPU).

**Comment by Psiche91** [comment]
Hello.

Oh, so simple.
Thx a lot.

Best
